# Generated by Django 4.1.2 on 2022-11-08 17:48

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Numero do telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.CharField(help_text='Endereço de e-mail', max_length=100, unique=True, verbose_name='E-MAIL')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={'thumbnai': {'crop': True, 'heigh': 100, 'width': 100}}, verbose_name='Foto')),
                ('endereco', models.CharField(help_text='Endereço completo', max_length=100, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
