# Generated by Django 4.1.2 on 2022-11-08 19:12

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={'thumbnai': {'crop': True, 'height': 100, 'width': 100}}, verbose_name='Foto'),
        ),
    ]
